### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Trickness** [wiiiky/jacques#1]
# Cannot build
I got success in runing:<pre><code>./configure</code></pre>
But when I run <pre><code>make</code></pre>
I got:
<pre><code>src/conf/Makefile.am:4: error: library used but 'RANLIB' is undefined
src/conf/Makefile.am:4:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'
src/conf/Makefile.am:4:   to 'configure.ac' and run 'autoconf' again.
src/io/Makefile.am:4: error: library used but 'RANLIB' is undefined
src/io/Makefile.am:4:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'
src/io/Makefile.am:4:   to 'configure.ac' and run 'autoconf' again.
Makefile:360: recipe for target 'Makefile.in' failed
make: *** [Makefile.in] Error 1</code></pre>

How can I fix this problem

**Comment by Trickness** [comment]
Did you fogite to make clean?
After I run <pre><code>make clean && make</code></pre>
it seems that this problem was fixed

**Comment by Trickness** [comment]
But another problem apperas
<pre><code>
$ make
......
......
  CC       libjio_a-jsocket.o
  CC       libjio_a-pack.o
  CC       libjio_a-jpoll.o
  CC       libjio_a-jfile.o
  AR       libjio.a
/bin/bash: @AR@: command not found
Makefile:398: recipe for target 'libjio.a' failed</code></pre>

I build this program on <pre><code>Linux Tricks 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux</code></pre>

**Comment by Trickness** [comment]
I currectly installed gcc,g++ and ar
<per><code>
GNU ar (GNU Binutils for Debian) 2.24.90.20141023
</code></pre>

**Comment by wiiiky** [comment]
我需要知道你autoconf和automake的版本

**Comment by Trickness** [comment]
計算機課下了………
('▽'〃) (顏文字
等我晚上回家再說

--- 原始邮件 ---

发件人： "Wiky L" <notifications@github.com>
已发： 2015年1月16日 下午3:10
收件人： "wiiiky/jacques" <jacques@noreply.github.com>
抄送： "张峻锋" <SternWZhang@outlook.com>
主题： Re: [jacques] Cannot build (#1)

我需要知道你autoconf和automake的版本

---

**Comment by Trickness** [comment]
<pre><code>
tricks@Tricks:~$ automake --version
automake (GNU automake) 1.14.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
</pre></code>

**Comment by wiiiky** [comment]
版本是一样的，我也不知道什么原因

**Comment by Trickness** [comment]
pull后得到解决，原因不明
